/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bentest.controllers;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ben.schellenberger
 */
public enum LastName {

    Ator,
    Atta,
    Attal,
    Baldassarre,
    Baldauf,
    Balde,
    Baldearena,
    Baldelli,
    Balden,
    Baldenegro,
    Balder,
    Balderama,
    Balderas,
    Balderrama,
    Balderree,
    Balderson,
    Balderston,
    Digman,
    Digmann,
    Dignan,
    Digness,
    Digrande,
    Digrazia,
    Digregorio,
    Digsby,
    Dihel,
    Diiorio,
    Smith,
    Poeschel,
    Poeschl,
    Poet,
    Poetker,
    Poette,
    Poetter,
    Poetzsch,
    Lav,
    Lava,
    Lavadera,
    Lavadie,
    Lavagnino,
    Lavala,
    Lavalais,
    Lavalette,
    Lavalla,
    Lavalle,
    Pofahl,
    Poff,
    Poffenberger,
    Poffenroth,
    Pelzer,
    Pember,
    Pemberton,
    Pemble,
    Pembleton,
    Pembroke,
    Pembrook,
    Pemelton,
    Pen,
    Pena,
    Penado,
    Penaflor,
    Penagos,
    Klappholz,
    Klar,
    Klarberg,
    Klare,
    Klaren,
    Klarich,
    Klarin,
    Klarman,
    Klarr,
    Klas,
    Klase,
    Klasen,
    Klasing,
    Klasinski,
    Klass,
    Klassen,
    Klatt,
    Klatte,
    Klauer,
    Klaus,
    Klauser,
    Klausner,
    Klave,
    Klaver,
    Klavetter,
    Klavon,
    Klavuhn,
    Klawinski,
    Klawiter,
    Klawitter,
    Klawuhn,
    Klay,
    Klayman,
    Klear,
    Kleban,
    Klebanoff,
    Klebanow,
    Klebe,
    Kleber,
    Klebes,
    Klecha,
    Kleck,
    Klecker,
    Kleckley,
    Kleckner,
    Klee,
    Kleeb,
    Kleefisch,
    Kleekamp,
    Kleeman,
    Kleen,
    Klees,
    Kleese,
    Kleespies,
    Kleffman,
    Kleffner,
    Kleftogiannis,
    Klegin;

    public static List<String> getNames() {
        List<String> list = new ArrayList<>();
        for ( LastName ln : values() ) {
            list.add( ln.name() );
        }
        return list;
    }
}
